const { GoogleGenerativeAI } = require('@google/generative-ai');
const Practice = require('../models/Practice');
const { calculateWPM } = require('../utils/wpmCalculator');
const { calculateAccuracy } = require('../utils/accuracyCalculator');
const { sendSuccess, sendError } = require('../utils/apiResponse');

const getGeminiModel = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return null;
  const genAI = new GoogleGenerativeAI(apiKey);
  return genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
};

const TOPICS = [
  'Education', 'Technology', 'Government', 'Economy', 'Society',
  'Health', 'Environment', 'Science', 'Sports', 'Law', 'Business', 'Culture',
];

// ── Local passage bank (used when Gemini API is unavailable) ──
const LOCAL_PASSAGES = {
  Education: [
    "Education is the foundation of a progressive society. It empowers individuals to think critically and make informed decisions in their daily lives. Schools and colleges play a vital role in shaping the future of our nation by nurturing young minds and preparing them for the challenges that lie ahead. Teachers are the backbone of the educational system, dedicating their lives to impart knowledge and wisdom to their students. The importance of quality education cannot be overstated, as it opens doors to better opportunities and helps bridge the gap between different sections of society. Modern education should focus not only on academic excellence but also on developing practical skills and emotional intelligence. Students must learn to collaborate, communicate effectively, and adapt to changing circumstances in an ever-evolving world. The government has a responsibility to ensure that every child has access to affordable and quality education regardless of their economic background. Investment in education is an investment in the future prosperity of the nation. Libraries, laboratories, and digital resources are essential tools that enhance the learning experience and make education more engaging for students of all ages. Parents also play a crucial role in supporting their children's educational journey by providing encouragement, guidance, and a conducive learning environment at home. The curriculum should be regularly updated to reflect the needs of modern society and the demands of the job market. Vocational training and skill development programmes should be given equal importance alongside traditional academic subjects. Education must promote values such as honesty, respect, tolerance, and social responsibility among the younger generation. The goal of education should be to create well-rounded individuals who can contribute meaningfully to society and lead fulfilling lives.",
    "The purpose of education extends beyond the mere acquisition of knowledge. It is about developing the whole person and preparing them for a meaningful and productive life. In recent years, there has been a growing emphasis on inclusive education that ensures every student, regardless of their abilities or disabilities, has the opportunity to learn and grow. Special education programmes have been designed to cater to the needs of students who require additional support. The use of technology in education has revolutionized the way we teach and learn. Online classes, digital textbooks, and educational apps have made learning more accessible than ever before. However, it is important to remember that technology is a tool and not a replacement for effective teaching. The role of the teacher remains central to the educational process. Good teachers inspire their students, ignite their curiosity, and help them discover their potential. Continuous professional development for teachers is essential to keep them updated with the latest teaching methods and educational research. Assessment and evaluation systems should be designed to measure not just rote learning but also critical thinking, creativity, and problem-solving skills. Examinations should be a means of learning rather than a source of stress and anxiety for students. The education system should encourage students to ask questions, explore new ideas, and develop a love for lifelong learning. Co-curricular activities such as sports, music, drama, and community service play an important role in the holistic development of students. These activities help build character, teamwork, and leadership skills that are essential for success in life."
  ],
  Technology: [
    "Technology has transformed every aspect of our lives in ways that were unimaginable just a few decades ago. From the way we communicate to how we work, shop, and entertain ourselves, technology has made the world smaller and more connected. The rapid advancement of digital technology has given rise to new industries and created millions of jobs around the globe. Smartphones have become an essential part of our daily lives, serving as our cameras, calendars, maps, and communication devices all in one. The internet has revolutionized access to information, making it possible for anyone with a connection to learn about virtually any topic. Social media platforms have changed the way we interact with each other, enabling people to stay connected across vast distances. However, the rise of technology has also brought challenges such as data privacy concerns, cybersecurity threats, and the digital divide between those who have access to technology and those who do not. Artificial intelligence and machine learning are rapidly changing the landscape of many industries, from healthcare to finance to transportation. These technologies have the potential to solve complex problems and improve efficiency in ways that were previously impossible. Cloud computing has enabled businesses of all sizes to access powerful computing resources without the need for expensive hardware. The development of renewable energy technologies is helping to address the climate crisis by reducing our dependence on fossil fuels. As technology continues to evolve at an unprecedented pace, it is crucial that we consider the ethical implications of new innovations and ensure that the benefits of technology are shared equitably across society.",
    "The digital revolution has fundamentally changed the way businesses operate and compete in the global marketplace. Companies that embrace new technologies are better positioned to innovate, reduce costs, and deliver superior products and services to their customers. E-commerce has transformed the retail industry, allowing consumers to shop from the comfort of their homes and giving small businesses access to a global customer base. The rise of remote work, accelerated by recent global events, has demonstrated that many jobs can be performed effectively from anywhere with an internet connection. This shift has implications for urban planning, transportation, and the future of office spaces. Cybersecurity has become a critical concern for organizations of all sizes as cyber attacks become more sophisticated and frequent. Protecting sensitive data and maintaining the trust of customers requires constant vigilance and investment in security measures. The Internet of Things is connecting everyday devices to the internet, creating smart homes, smart cities, and smart factories that can operate more efficiently. Blockchain technology is being explored for applications beyond cryptocurrency, including supply chain management, voting systems, and digital identity verification. Quantum computing, while still in its early stages, promises to revolutionize computing by solving problems that are currently beyond the reach of classical computers. The tech industry has a responsibility to develop products and services that are accessible to people with disabilities and to address issues of bias in algorithms and artificial intelligence systems."
  ],
  Government: [
    "The role of government in a democratic society is to serve the people and ensure their welfare. Good governance is characterized by transparency, accountability, and responsiveness to the needs of citizens. The government is responsible for maintaining law and order, protecting the rights and freedoms of individuals, and providing essential public services such as healthcare, education, and infrastructure. In a democracy, the power of the government is derived from the consent of the governed, and elected representatives have a duty to act in the best interests of their constituents. Public policy should be based on evidence and informed by consultation with stakeholders and experts. The legislative process involves careful deliberation and debate to ensure that laws are fair, just, and effective. The judiciary plays a crucial role in upholding the rule of law and protecting the rights of citizens against any abuse of power. Local government institutions are closer to the people and are better positioned to address the specific needs and concerns of their communities. Decentralization of power can lead to more efficient and responsive governance. The government must also play a role in regulating the economy, protecting consumers, and ensuring fair competition in the marketplace. International cooperation and diplomacy are essential for addressing global challenges such as climate change, terrorism, and pandemics. Citizens have both rights and responsibilities in a democracy, including the duty to participate in the democratic process through voting and civic engagement. A well-functioning democracy requires an informed and engaged citizenry that holds its leaders accountable.",
    "Public administration is the implementation of government policy and the management of public programmes. Effective public administration requires skilled and dedicated civil servants who are committed to serving the public interest. The bureaucracy plays an essential role in translating the decisions of elected officials into concrete actions and programmes that benefit citizens. Administrative reforms are often necessary to improve efficiency, reduce red tape, and enhance the quality of public services. E-governance initiatives have the potential to make government services more accessible and transparent by leveraging digital technology. Online portals and mobile applications allow citizens to access government services, file complaints, and track the status of their requests without having to visit government offices in person. The Right to Information empowers citizens to seek information from public authorities, thereby promoting transparency and accountability in government. Anti-corruption measures are crucial for maintaining public trust in government institutions. Whistleblower protection laws encourage individuals to report corruption and wrongdoing without fear of retaliation. The government must ensure that its policies are inclusive and that the benefits of development reach all sections of society, especially the marginalized and disadvantaged. Social welfare programmes play a vital role in providing a safety net for the most vulnerable members of society. The success of government programmes depends on effective implementation, monitoring, and evaluation to ensure that resources are being used efficiently and that the intended outcomes are being achieved."
  ],
  Economy: [
    "The economy is the backbone of any nation, and its health directly affects the well-being of every citizen. Economic growth creates jobs, increases incomes, and improves the standard of living for people across all sections of society. A strong and diversified economy is more resilient to external shocks and better able to withstand periods of uncertainty. The government plays a crucial role in creating an enabling environment for economic growth through sound fiscal and monetary policies. Investment in infrastructure such as roads, railways, ports, and airports is essential for facilitating trade and commerce. Small and medium enterprises are the engine of economic growth in most countries, providing employment to millions of people and contributing significantly to the national output. Access to affordable credit and financial services is critical for the growth of these enterprises. The agricultural sector remains an important source of livelihood for a large proportion of the population in many developing countries. Modernizing agriculture through the adoption of new technologies and practices can significantly improve productivity and incomes for farmers. International trade allows countries to specialize in the production of goods and services in which they have a comparative advantage, leading to greater efficiency and prosperity. However, the benefits of trade must be distributed fairly, and workers who are displaced by globalization must be provided with support and retraining opportunities. Inflation, unemployment, and fiscal deficits are key challenges that policymakers must address to ensure sustainable economic growth.",
    "Financial literacy is essential for individuals to make informed decisions about saving, investing, and managing their money. The banking system plays a central role in the economy by mobilizing savings and channeling them into productive investments. A well-regulated financial sector is important for maintaining stability and preventing crises. The stock market provides companies with access to capital and gives investors the opportunity to share in the profits of successful businesses. However, investing in the stock market carries risks, and individuals should educate themselves before making investment decisions. Taxation is the primary means by which the government raises revenue to fund public services and infrastructure. A fair and efficient tax system is essential for generating the resources needed for development while minimizing the burden on taxpayers. Budget planning and fiscal discipline are important for ensuring that government spending is sustainable and that public debt does not reach unsustainable levels. The informal economy, which includes unregistered businesses and unreported income, represents a significant portion of economic activity in many developing countries. Formalizing this sector can broaden the tax base and provide workers with greater protections and benefits. Digital payment systems and financial technology innovations are transforming the way people conduct transactions and manage their finances. These innovations have the potential to increase financial inclusion by bringing banking services to underserved populations."
  ],
  Society: [
    "Society is a complex web of relationships and interactions that binds people together in a shared community. The strength of a society lies in its diversity and its ability to accommodate different perspectives, cultures, and ways of life. Social cohesion is built on mutual respect, understanding, and a shared commitment to the common good. Every individual has a role to play in creating a just and equitable society where everyone has the opportunity to thrive. Social justice requires that the rights of all citizens are protected and that the benefits of development are shared fairly. Discrimination based on caste, religion, gender, or any other basis has no place in a civilized society. Education and awareness are powerful tools for combating prejudice and promoting tolerance. The family is the basic unit of society and plays a crucial role in socializing children and instilling values. Strong families create strong communities, and strong communities create a strong nation. The empowerment of women is essential for the progress of society as a whole. When women are educated and empowered, families are healthier, communities are more prosperous, and nations are more stable. Youth are the future of any society, and investing in their education, health, and development is an investment in the future. Social media has created new opportunities for people to connect, share ideas, and organize for social change. However, it has also raised concerns about online harassment, misinformation, and the impact of excessive screen time on mental health. Community organizations and civil society groups play an important role in addressing social issues and advocating for the rights of marginalized groups.",
    "Urbanization is one of the most significant social trends of our time, with more people living in cities than ever before. Cities offer opportunities for employment, education, and cultural enrichment, but they also face challenges such as overcrowding, pollution, and inadequate infrastructure. Planned urban development is essential for creating livable and sustainable cities that meet the needs of their residents. Housing is a basic human need, and ensuring that affordable and adequate housing is available to all is a key social challenge. Homelessness is a complex issue that requires a comprehensive approach involving social services, mental health support, and affordable housing programmes. Public transportation systems are vital for connecting people to jobs, education, and services, and for reducing traffic congestion and air pollution in urban areas. The preservation of cultural heritage is important for maintaining a sense of identity and continuity in a rapidly changing world. Museums, libraries, and cultural institutions play a valuable role in preserving and sharing our collective heritage. Volunteerism and community service are expressions of civic responsibility and contribute to the well-being of society. Encouraging young people to volunteer helps them develop empathy, leadership skills, and a sense of social responsibility. Mental health awareness has increased significantly in recent years, and there is growing recognition that mental health is just as important as physical health. Reducing the stigma associated with mental illness and improving access to mental health services are important priorities for society."
  ],
  Health: [
    "Health is the most precious asset that any individual possesses, and maintaining good health should be a priority for everyone. A healthy population is essential for the economic and social development of any nation. The healthcare system must be accessible, affordable, and of high quality to meet the needs of all citizens. Prevention is better than cure, and public health programmes that focus on disease prevention and health promotion can significantly reduce the burden of illness. Regular exercise, a balanced diet, adequate sleep, and stress management are the cornerstones of a healthy lifestyle. The importance of mental health has gained increasing recognition in recent years, and there is a growing understanding that mental and physical health are closely interconnected. Access to clean water and sanitation is a fundamental requirement for good health and the prevention of waterborne diseases. Immunization programmes have been one of the most successful public health interventions in history, saving millions of lives by protecting people against deadly diseases. The training and retention of healthcare professionals is critical for ensuring that quality healthcare services are available in both urban and rural areas. Community health workers play an important role in providing basic healthcare services and health education in underserved communities. The use of technology in healthcare, including telemedicine and electronic health records, has the potential to improve the quality and efficiency of care. Research and development of new medicines and treatments is essential for addressing emerging health challenges and improving patient outcomes.",
    "The global health landscape is constantly evolving, with new challenges and opportunities emerging regularly. Non-communicable diseases such as heart disease, diabetes, and cancer have become the leading causes of death worldwide, and addressing these requires a comprehensive approach that includes prevention, early detection, and treatment. Tobacco use, excessive alcohol consumption, unhealthy diets, and physical inactivity are major risk factors for non-communicable diseases that can be modified through public health interventions and individual behaviour change. Maternal and child health remains a priority in many developing countries, where access to quality prenatal care, skilled birth attendants, and post-natal care can significantly reduce maternal and infant mortality. Nutrition plays a critical role in the health and development of children, and malnutrition in early childhood can have lasting effects on physical and cognitive development. The pharmaceutical industry plays a valuable role in developing and producing medicines that save lives and improve quality of life. However, the cost of medicines can be a barrier to access, particularly in developing countries. Generic medicines provide a more affordable alternative to brand-name drugs and play an important role in improving access to essential treatments. Health insurance and social health protection schemes can help protect individuals and families from the financial burden of illness. Emergency preparedness and response capabilities are essential for dealing with disease outbreaks, natural disasters, and other health emergencies."
  ],
  Environment: [
    "The environment is the natural world that surrounds us and sustains all life on earth. Protecting the environment is not just a moral obligation but a necessity for the survival of future generations. Climate change is one of the most pressing challenges facing humanity today, and urgent action is needed to reduce greenhouse gas emissions and limit global warming. Deforestation, industrial pollution, and the burning of fossil fuels are major contributors to climate change and environmental degradation. Renewable energy sources such as solar, wind, and hydroelectric power offer a cleaner alternative to fossil fuels and can help reduce our carbon footprint. Conservation of biodiversity is essential for maintaining the health of ecosystems and the services they provide, including clean air, clean water, and food production. Many plant and animal species are facing extinction due to habitat loss, pollution, and climate change, and protecting endangered species requires coordinated efforts at local, national, and international levels. Sustainable development seeks to meet the needs of the present without compromising the ability of future generations to meet their own needs. Waste management is a growing concern, and reducing, reusing, and recycling materials can significantly decrease the amount of waste that ends up in landfills and oceans. Plastic pollution has become a global crisis, with millions of tonnes of plastic entering the oceans each year, harming marine life and ecosystems. Water scarcity is a serious issue in many parts of the world, and efficient water management and conservation practices are essential for ensuring a reliable supply of clean water for all.",
    "Environmental education is crucial for raising awareness about the importance of protecting our natural resources and inspiring people to take action. Tree planting campaigns and reforestation efforts can help restore degraded lands and absorb carbon dioxide from the atmosphere. Urban green spaces such as parks and gardens improve air quality, reduce the urban heat island effect, and provide recreational opportunities for residents. Organic farming practices avoid the use of synthetic pesticides and fertilizers, promoting healthier soils and reducing pollution of waterways. The concept of a circular economy, where products are designed to be reused, repaired, and recycled, offers a more sustainable alternative to the traditional linear model of take, make, and dispose. Environmental impact assessments are an important tool for evaluating the potential effects of proposed development projects on the environment and ensuring that appropriate mitigation measures are put in place. International agreements such as the Paris Agreement on climate change represent important steps towards global cooperation on environmental issues. However, achieving the targets set by these agreements requires sustained commitment and action from all countries. Every individual can make a difference by adopting environmentally friendly practices in their daily lives, such as conserving energy, reducing water waste, using public transportation, and choosing sustainable products."
  ],
  Science: [
    "Science is the systematic study of the natural world through observation and experimentation. It has been the driving force behind many of the greatest achievements in human history, from the discovery of electricity to the development of vaccines that have saved countless lives. The scientific method, which involves formulating hypotheses, conducting experiments, and analyzing data, is a powerful tool for understanding the world around us. Research in the basic sciences such as physics, chemistry, and biology continues to expand our knowledge and lead to new discoveries that have practical applications in everyday life. Space exploration has captured the imagination of people around the world and has led to remarkable achievements such as landing on the moon and sending probes to distant planets. The study of the universe helps us understand our place in the cosmos and inspires future generations of scientists and explorers. Advances in medical science have dramatically improved our ability to diagnose, treat, and prevent diseases, leading to longer and healthier lives. Genetics and genomics are revolutionizing our understanding of heredity and enabling the development of personalized medicine tailored to individual patients. Neuroscience is shedding light on the mysteries of the brain and mind, with implications for treating neurological and psychiatric disorders. Environmental science is helping us understand the complex interactions between human activities and natural systems, and informing efforts to address environmental challenges. Scientific literacy is essential for citizens to make informed decisions about issues that affect their lives and the world around them.",
    "The history of science is marked by paradigm shifts that have fundamentally changed our understanding of the natural world. From the Copernican revolution that placed the sun at the center of the solar system to the theory of evolution that explained the diversity of life on earth, scientific breakthroughs have time and again challenged our assumptions and expanded our horizons. Modern physics, including the theories of relativity and quantum mechanics, has revealed a universe that is far stranger and more wonderful than anyone could have imagined. Chemistry has given us an understanding of the properties and behaviour of matter at the atomic and molecular level, leading to the development of new materials, medicines, and technologies. Biotechnology is a rapidly growing field that applies biological knowledge and techniques to develop products and processes that benefit society. The Human Genome Project, which mapped the entire human genetic code, was a landmark achievement that has opened up new possibilities for understanding and treating genetic diseases. Science communication plays an important role in bridging the gap between scientists and the public, making complex scientific concepts accessible to a wider audience. Encouraging young people to pursue careers in science, technology, engineering, and mathematics is important for ensuring a steady supply of skilled researchers and innovators. Ethical considerations are increasingly important in scientific research, particularly in areas such as genetic engineering, artificial intelligence, and human experimentation."
  ],
  Sports: [
    "Sports play a vital role in promoting physical fitness, mental well-being, and social interaction. Regular participation in sports and physical activities helps individuals maintain a healthy weight, strengthen their muscles and bones, and reduce the risk of chronic diseases. Beyond the physical benefits, sports teach valuable life skills such as teamwork, discipline, perseverance, and sportsmanship. From a young age, children who participate in sports learn the importance of setting goals, working hard, and dealing with both success and failure. School sports programmes provide students with opportunities to discover their talents and develop their athletic abilities. Community sports clubs and recreational facilities play an important role in bringing people together and fostering a sense of belonging. Professional sports have become a major industry, generating billions in revenue and providing entertainment to millions of fans around the world. Major sporting events such as the Olympics and the World Cup bring nations together and celebrate the highest levels of athletic achievement. However, the commercialization of sports has also raised concerns about issues such as doping, corruption, and the exploitation of young athletes. Ensuring fair play and integrity in sports requires strong governance, effective regulations, and a commitment to ethical standards. Sports can also be a powerful tool for social change, promoting gender equality, breaking down barriers, and inspiring people to overcome adversity. Adaptive sports programmes provide opportunities for people with disabilities to participate in athletics and experience the many benefits of physical activity.",
    "The evolution of sports over the centuries reflects the changing values and priorities of society. Ancient civilizations used sports and athletic competitions to train warriors, honour their gods, and entertain their citizens. Today, sports continue to be an important part of our cultural fabric, bringing joy and excitement to people of all ages and backgrounds. Fitness and wellness trends have led to a growing interest in activities such as yoga, running, cycling, and swimming, which can be enjoyed by people of all fitness levels. The role of coaches and trainers in developing athletes cannot be overstated, as they provide guidance, motivation, and technical expertise. Sports science has advanced our understanding of human performance, nutrition, injury prevention, and recovery, enabling athletes to train more effectively and compete at higher levels. The use of technology in sports, including video analysis, wearable devices, and data analytics, has transformed the way teams prepare for and analyze competitions. Fan engagement has been enhanced through social media, streaming platforms, and interactive experiences that bring fans closer to the action. Youth sports development programmes are essential for identifying and nurturing talented young athletes who may one day represent their country on the international stage. The values of fair play, respect, and integrity must be at the heart of all sporting endeavours, from grassroots participation to elite competition."
  ],
  Law: [
    "The law is the foundation of a civilized society, providing the rules and principles that govern the behaviour of individuals and institutions. A well-functioning legal system ensures that justice is served, rights are protected, and disputes are resolved fairly and impartially. The rule of law is a fundamental principle that means everyone, regardless of their position or power, is subject to and accountable under the law. The constitution is the supreme law of the land, setting out the fundamental rights and duties of citizens and the structure and powers of government. Constitutional courts play a vital role in interpreting the constitution and ensuring that laws and government actions are consistent with constitutional principles. Criminal law deals with offences against society and prescribes punishments for those found guilty of criminal behaviour. The criminal justice system must balance the need to protect society with the rights of the accused, including the right to a fair trial, the presumption of innocence, and the right to legal representation. Civil law governs disputes between individuals and organizations, including matters related to contracts, property, family, and torts. The legal profession plays a crucial role in ensuring access to justice, and lawyers have a duty to act with integrity and in the best interests of their clients. Legal aid programmes are essential for ensuring that individuals who cannot afford legal representation have access to justice. The judiciary must be independent from political influence to ensure that justice is administered impartially and without fear or favour.",
    "Human rights are the basic rights and freedoms that belong to every person in the world, regardless of their nationality, sex, ethnicity, religion, or any other status. International human rights law sets out the obligations of governments to act in certain ways or to refrain from certain acts in order to promote and protect the human rights of individuals and groups. The Universal Declaration of Human Rights, adopted by the United Nations in nineteen forty-eight, is a milestone document that sets out the fundamental human rights to be universally protected. Freedom of speech, freedom of religion, the right to education, and the right to a fair trial are among the many rights enshrined in international human rights instruments. Consumer protection laws are designed to safeguard the interests of consumers and ensure that businesses operate fairly and honestly. Environmental law is an increasingly important area that regulates human activities that affect the natural environment and seeks to prevent pollution and environmental degradation. Labour law governs the relationship between employers and employees, setting standards for wages, working hours, workplace safety, and the right to organize and bargain collectively. Intellectual property law protects the rights of creators and inventors by granting them exclusive rights over their works and inventions for a specified period. The legal system must continue to evolve and adapt to address new challenges and issues that arise in an increasingly complex and interconnected world."
  ],
  Business: [
    "Business is the engine of economic growth and development, creating jobs, generating wealth, and driving innovation. Successful businesses are built on a foundation of strong leadership, clear strategy, and a commitment to delivering value to their customers. Entrepreneurship is the process of identifying opportunities and creating new ventures to take advantage of those opportunities. Entrepreneurs are risk-takers who are willing to invest their time, energy, and resources in pursuit of their vision. Small and medium enterprises form the backbone of most economies, providing employment to a significant portion of the workforce and contributing to economic diversity. Effective management involves planning, organizing, leading, and controlling resources to achieve organizational goals. Leadership is about inspiring and motivating people to work together towards a common purpose. Communication skills are essential for business success, as clear and effective communication helps build relationships, resolve conflicts, and drive results. Marketing is the process of understanding customer needs and developing products and services that meet those needs. A strong brand identity helps companies differentiate themselves from competitors and build customer loyalty. Financial management involves planning and managing an organization's financial resources to ensure long-term sustainability and growth. Human resource management is concerned with recruiting, developing, and retaining talented employees who can contribute to the success of the organization. Corporate social responsibility encourages businesses to consider the impact of their actions on society and the environment and to operate in a sustainable and ethical manner.",
    "The business landscape is constantly evolving, driven by technological innovation, changing consumer preferences, and global competition. Companies that are able to adapt quickly to changing market conditions are more likely to succeed in the long run. Strategic planning involves setting long-term goals and developing plans to achieve them, taking into account the organization's strengths, weaknesses, opportunities, and threats. Innovation is the key to staying competitive in today's fast-paced business environment. Companies that invest in research and development and encourage creative thinking among their employees are better positioned to develop new products, services, and processes that give them a competitive edge. Customer service is a critical differentiator in many industries, and companies that consistently deliver excellent customer experiences are rewarded with loyal customers and positive word of mouth. Supply chain management involves coordinating the flow of goods, information, and finances from raw materials to finished products delivered to the end customer. Effective supply chain management can reduce costs, improve quality, and enhance customer satisfaction. Business ethics is concerned with applying ethical principles to business activities and decisions. Companies that operate with integrity and transparency build trust with their stakeholders and create a positive reputation in the marketplace. Globalization has created new opportunities for businesses to expand into international markets, but it also brings challenges such as navigating different regulatory environments, cultural differences, and currency fluctuations."
  ],
  Culture: [
    "Culture encompasses the beliefs, values, customs, traditions, and artistic expressions that define a community or society. It is the lens through which we interpret the world and gives meaning to our experiences. Cultural diversity is a source of strength and richness, as it brings together different perspectives and ways of life that can inspire creativity and innovation. Preserving and celebrating cultural heritage is important for maintaining a sense of identity and continuity across generations. Traditional art forms such as music, dance, painting, and sculpture are expressions of human creativity that have been passed down through centuries. Literature, poetry, and storytelling are powerful means of communicating ideas, emotions, and experiences across time and space. Festivals and cultural celebrations bring communities together and provide opportunities to share joy, strengthen bonds, and honour traditions. Museums and cultural institutions play a vital role in preserving artifacts and artworks that tell the story of human civilization. The performing arts, including theatre, opera, and ballet, offer audiences a unique and immersive experience that can entertain, educate, and inspire. Cinema and film have become one of the most influential cultural mediums, reaching audiences around the world and shaping popular culture. Architecture reflects the aesthetic sensibilities and technological capabilities of different periods and cultures, and historic buildings and monuments are treasured landmarks that attract visitors from around the world. Cultural exchange programmes promote understanding and friendship between people of different backgrounds and nationalities.",
    "The role of culture in shaping individual and collective identity cannot be underestimated. Language is one of the most important elements of culture, serving as the primary means of communication and a carrier of cultural knowledge and traditions. The preservation of indigenous and minority languages is important for maintaining cultural diversity and ensuring that the knowledge and wisdom embedded in these languages are not lost. Food and cuisine are integral parts of culture, reflecting the history, geography, and values of a community. Culinary traditions are passed down through generations and often serve as a source of pride and identity. Handicrafts and traditional crafts represent the artistic skills and creativity of artisans and are an important source of livelihood in many communities. Supporting traditional crafts helps preserve cultural heritage and provides economic opportunities for skilled artisans. The globalization of culture, facilitated by mass media and the internet, has led to both the spread of cultural ideas and concerns about cultural homogenization. It is important to find a balance between embracing global cultural influences and preserving local cultural identities. Cultural policies and programmes can help promote cultural participation, support artists and cultural organizations, and ensure that cultural resources are accessible to all members of society. Education plays a key role in transmitting cultural values and knowledge to the next generation, and cultural education should be an integral part of the school curriculum."
  ],
};

/**
 * Build a passage from the local bank, repeating/trimming sentences to hit the target word count.
 */
const generateLocalPassage = (topic, wordCount) => {
  const topicPassages = LOCAL_PASSAGES[topic] || LOCAL_PASSAGES['Education'];
  const base = topicPassages[Math.floor(Math.random() * topicPassages.length)];
  const sentences = base.match(/[^.!?]+[.!?]+/g) || [base];

  let words = [];
  let idx = 0;
  while (words.length < wordCount) {
    const s = sentences[idx % sentences.length].trim();
    words.push(...s.split(/\s+/));
    idx++;
  }

  return words.slice(0, wordCount).join(' ');
};

const generateDictation = async (req, res, next) => {
  try {
    const { topic, wpm, duration } = req.body;

    const speed = parseInt(wpm);
    const dur = parseInt(duration);
    if (!speed || speed < 40 || speed > 200) return sendError(res, 400, 'WPM must be between 40 and 200');
    if (!dur || dur < 1 || dur > 10) return sendError(res, 400, 'Duration must be between 1 and 10 minutes');

    const wordCount = speed * dur;
    const chosenTopic = topic || TOPICS[Math.floor(Math.random() * TOPICS.length)];

    // Try Gemini first, fall back to local passages
    let text;
    let source = 'ai';

    const model = getGeminiModel();
    if (model) {
      try {
        const prompt = `Generate a stenography dictation passage for practice.

Topic: ${chosenTopic}
Required word count: exactly ${wordCount} words
Speed target: ${speed} words per minute
Duration: ${dur} minutes

Instructions:
- Write in clear spoken English suitable for stenography students.
- The passage must be exactly ${wordCount} words long.
- Use natural dictation style like a teacher speaking aloud.
- Use simple to moderate vocabulary. Avoid very difficult or technical words.
- Include proper punctuation (commas, periods, semicolons) where necessary.
- Do not include any headings, titles, bullet points, or formatting.
- Return ONLY the dictation passage text, nothing else.`;

        const result = await model.generateContent(prompt);
        text = result.response.text().trim();
      } catch (aiErr) {
        // AI failed — use local fallback
        text = null;
      }
    }

    if (!text) {
      text = generateLocalPassage(chosenTopic, wordCount);
      source = 'local';
    }

    sendSuccess(res, 200, 'Dictation generated', {
      passage: text,
      topic: chosenTopic,
      wpm: speed,
      duration: dur,
      targetWordCount: wordCount,
      actualWordCount: text.split(/\s+/).length,
      source,
    });
  } catch (error) {
    next(error);
  }
};

const submitAIPractice = async (req, res, next) => {
  try {
    const { transcript, typedText, timeTaken, topic } = req.body;

    if (!transcript || !typedText) return sendError(res, 400, 'Transcript and typed text are required');
    if (!timeTaken || timeTaken < 1) return sendError(res, 400, 'Invalid time taken');

    const wpm = calculateWPM(typedText, timeTaken);
    const { accuracy, mistakeCount } = calculateAccuracy(transcript, typedText);

    const practice = await Practice.create({
      studentId: req.user._id,
      isAI: true,
      aiTopic: topic || 'Random',
      transcript,
      typedText,
      accuracy,
      wpm,
      timeTaken,
      mistakeCount,
    });

    sendSuccess(res, 201, 'AI Practice submitted', {
      practice: { _id: practice._id, wpm, accuracy, mistakeCount, timeTaken },
    });
  } catch (error) {
    next(error);
  }
};

const getTopics = (req, res) => {
  sendSuccess(res, 200, 'Topics fetched', { topics: TOPICS });
};

module.exports = { generateDictation, submitAIPractice, getTopics };
